In [1]:
import pandas as pd
PATH = "~/data/movies/dailyboxoffice/dt=20240101"
df = pd.read_parquet(PATH)
len(df)

df.groupby(['multiMovieYn', 'repNationCd'], dropna=False, observed=False) \
.size() \
.reset_index(name='count')

  multiMovieYn repNationCd  count
0            N           F      0
1            N           K      0
2            N         NaN     10
3            Y           F      0
4            Y           K      0
5            Y         NaN     10
6          NaN           F     10
7          NaN           K     10
8          NaN         NaN     10

In [3]:
len(df)

50

In [4]:
print(df.sample(10))

    rnum  rank  rankInten rankOldAndNew   movieCd  \
20     1     1          0           OLD  20234114
12     3     3          0           OLD  20236146
7      8     8          0           OLD  20234114
11     2     2          0           OLD  20212866
23     4     4          0           OLD  20233299
27     8     8          2           OLD  20124722
16     7     7         -1           OLD  20235290
21     2     2          0           OLD  20236045
49    10    10          3           OLD  20227525
6      7     7         -1           OLD  20235290

                                 movieNm      openDt    salesAmt  salesShare  \
20                                    괴물  2023-11-29    92381680        37.0
12  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~  2023-12-22   565417320         7.8
7                                     괴물  2023-11-29    92381680         1.2
11                                 서울의 봄  2023-11-22  2666429137        37.0
23                                  크레센도  2023-12-20    29203100        11.7
27                             피아니스트의 전설  2020-01-01     3063078         1.2
16                             도티와 영원의 탑  2023-12-27   100024717         1.4
21  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!  2023-12-27    53094530        21.3
49                             교토에서 온 편지  2023-12-06      207000         0.0
6                              도티와 영원의 탑  2023-12-27   100024717         1.3

    salesInten  salesChange      salesAcc  audiCnt  audiInten  audiChange  \
20    -3768994         -3.9    3884333955     8710       -524        -5.7
12   -69888800        -11.0    6071745009    58239      -6751       -10.4
7     -3768994         -3.9    3884333955     8710       -524        -5.7
11  -649456909        -19.6  118016920547   262422     -64054       -19.6
23    -2644200         -8.3     424298400     2534       -235        -8.5
27    -1092200        -26.3     416989591      294       -142       -32.6
16   -13487835        -11.9     488186693    10704      -1268       -10.6
21     -707720         -1.3     372974290     6471         67         1.0
49      -67800        -24.7      58288197       29        -19       -39.6
6    -13487835        -11.9     488186693    10704      -1268       -10.6

     audiAcc  scrnCnt  showCnt multiMovieYn repNationCd
20    396137      187      263            Y         NaN
12    626508      834     1671            N         NaN
7     396137      187      263          NaN         NaN
11  12117201     1614     5444            N         NaN
23     39445       79      102            Y         NaN
27     51876       23       25            Y         NaN
16     52400      357      419            N         NaN
21     45294      207      248            Y         NaN
49      6717        3        3          NaN           K
6      52400      357      419          NaN         NaN

In [5]:
for _, row in df.iterrows():
    if pd.isna(row['multiMovieYn']):
        print(f"{row['movieCd']}")

# 출력
20203702
20212866
20236146
20235735
20235596

20203702
20212866
20236146
20235735
20235596
20234673
20235290
20234114
20236045
20235980
20236146
20235735
20235596
20234114
20236045
20235980
20236080
20233299
20235923
20235693
20203702
20212866
20234673
20235290
20190324
20202247
20228560
20235697
20232077
20227525

20235596

In [7]:
r = df[df['movieCd'] == '20203702'][['movieCd', 'movieNm', 'multiMovieYn', 'repNationCd']]
# pdm add -dG note tabulate
print(r.to_markdown())

|    |   movieCd | movieNm           | multiMovieYn   | repNationCd   |
|---:|----------:|:------------------|:---------------|:--------------|
|  0 |  20203702 | 노량: 죽음의 바다 | nan            | nan           |
| 10 |  20203702 | 노량: 죽음의 바다 | N              | nan           |
| 40 |  20203702 | 노량: 죽음의 바다 | nan            | K             |

In [8]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 'movieCd'를 기준으로 그룹화하여, 각 그룹의 'multiMovieYn'과 'repNationCd' 컬럼을 처리
df_clean = df.groupby('movieCd', as_index=False).agg({
    'multiMovieYn': first_non_null,
    'repNationCd': first_non_null
})

In [9]:
print(df_clean)

     movieCd multiMovieYn repNationCd
0   19860125            Y         NaN
1   20124722            Y         NaN
2   20190324            N           K
3   20202247          NaN           K
4   20203702            N           K
5   20212866            N           K
6   20227525          NaN           K
7   20228560          NaN           K
8   20232077          NaN           K
9   20233299            Y           F
10  20234114            Y           F
11  20234664            Y         NaN
12  20234673            N           K
13  20235098            N         NaN
14  20235290            N           K
15  20235596            N           F
16  20235693            Y           F
17  20235697          NaN           K
18  20235735            N           F
19  20235923            Y           F
20  20235980            N           F
21  20236045            Y           F
22  20236080            Y           F
23  20236146            N           F
24  20236533            Y         NaN

In [10]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 'movieCd'를 기준으로 그룹화하여, movieNm, multiMovieYn, repNationCd 컬럼을 처리
df_clean = df.groupby('movieCd', as_index=False).agg({
    'movieNm': first_non_null,
    'multiMovieYn': first_non_null,
    'repNationCd': first_non_null
})

# 결과 출력
print(df_clean)

     movieCd                               movieNm multiMovieYn repNationCd
0   19860125                                  쿼바디스            Y         NaN
1   20124722                             피아니스트의 전설            Y         NaN
2   20190324                                3일의 휴가            N           K
3   20202247                               싱글 인 서울          NaN           K
4   20203702                            노량: 죽음의 바다            N           K
5   20212866                                 서울의 봄            N           K
6   20227525                             교토에서 온 편지          NaN           K
7   20228560                                  너와 나          NaN           K
8   20232077                                어른 김장하          NaN           K
9   20233299                                  크레센도            Y           F
10  20234114                                    괴물            Y           F
11  20234664                        그대들은 어떻게 살 것인가            Y         NaN
12  20234673                      뽀로로 극장판 슈퍼스타 대모험            N           K
13  20235098                                  나폴레옹            N         NaN
14  20235290                             도티와 영원의 탑            N           K
15  20235596                            트롤: 밴드 투게더            N           F
16  20235693                             리빙: 어떤 인생            Y           F
17  20235697                엔시티 네이션 : 투 더 월드 인 시네마          NaN           K
18  20235735                          아쿠아맨과 로스트 킹덤            N           F
19  20235923                            사랑은 낙엽을 타고            Y           F
20  20235980                             말하고 싶은 비밀            N           F
21  20236045  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!            Y           F
22  20236080                         류이치 사카모토: 오퍼스            Y           F
23  20236146  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~            N           F
24  20236533                                립세의 사계            Y         NaN

In [13]:
ㅊ

# 결과 DataFrame을 마크다운 형식으로 출력
print(df_clean.to_markdown())

|    |   movieCd | openDt     | movieNm                                                       | multiMovieYn   | repNationCd   |
|---:|----------:|:-----------|:--------------------------------------------------------------|:---------------|:--------------|
|  0 |  19860125 | 1973-01-13 | 쿼바디스                                                      | Y              | nan           |
|  1 |  20124722 | 2020-01-01 | 피아니스트의 전설                                             | Y              | nan           |
|  2 |  20190324 | 2023-12-06 | 3일의 휴가                                                    | N              | K             |
|  3 |  20202247 | 2023-11-29 | 싱글 인 서울                                                  | nan            | K             |
|  4 |  20203702 | 2023-12-20 | 노량: 죽음의 바다                                             | N              | K             |
|  5 |  20212866 | 2023-11-22 | 서울의 봄                                                     | N              | K             |
|  6 |  20227525 | 2023-12-06 | 교토에서 온 편지                                              | nan            | K             |
|  7 |  20228560 | 2023-10-25 | 너와 나                                                       | nan            | K             |
|  8 |  20232077 | 2023-11-15 | 어른 김장하                                                   | nan            | K             |
|  9 |  20233299 | 2023-12-20 | 크레센도                                                      | Y              | F             |
| 10 |  20234114 | 2023-11-29 | 괴물                                                          | Y              | F             |
| 11 |  20234664 | 2023-10-25 | 그대들은 어떻게 살 것인가                                     | Y              | nan           |
| 12 |  20234673 | 2023-12-13 | 뽀로로 극장판 슈퍼스타 대모험                                 | N              | K             |
| 13 |  20235098 | 2023-12-06 | 나폴레옹                                                      | N              | nan           |
| 14 |  20235290 | 2023-12-27 | 도티와 영원의 탑                                              | N              | K             |
| 15 |  20235596 | 2023-12-20 | 트롤: 밴드 투게더                                             | N              | F             |
| 16 |  20235693 | 2023-12-13 | 리빙: 어떤 인생                                               | Y              | F             |
| 17 |  20235697 | 2023-12-06 | 엔시티 네이션 : 투 더 월드 인 시네마                          | nan            | K             |
| 18 |  20235735 | 2023-12-20 | 아쿠아맨과 로스트 킹덤                                        | N              | F             |
| 19 |  20235923 | 2023-12-20 | 사랑은 낙엽을 타고                                            | Y              | F             |
| 20 |  20235980 | 2023-12-13 | 말하고 싶은 비밀                                              | N              | F             |
| 21 |  20236045 | 2023-12-27 | 바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라! | Y              | F             |
| 22 |  20236080 | 2023-12-27 | 류이치 사카모토: 오퍼스                                       | Y              | F             |
| 23 |  20236146 | 2023-12-22 | 신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~ | N              | F             |
| 24 |  20236533 | 2024-01-10 | 립세의 사계                                                   | Y              | nan           |

In [14]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 'movieCd'를 인덱스로 사용하여 그룹화 및 집계
df_clean = df.groupby('movieCd').agg({
    'movieNm': first_non_null,
    'multiMovieYn': first_non_null,
    'repNationCd': first_non_null
})

# 결과 DataFrame을 마크다운 형식으로 인덱스와 함께 출력
print(df_clean.to_markdown(index=True))

|   movieCd | movieNm                                                       | multiMovieYn   | repNationCd   |
|----------:|:--------------------------------------------------------------|:---------------|:--------------|
|  19860125 | 쿼바디스                                                      | Y              | nan           |
|  20124722 | 피아니스트의 전설                                             | Y              | nan           |
|  20190324 | 3일의 휴가                                                    | N              | K             |
|  20202247 | 싱글 인 서울                                                  | nan            | K             |
|  20203702 | 노량: 죽음의 바다                                             | N              | K             |
|  20212866 | 서울의 봄                                                     | N              | K             |
|  20227525 | 교토에서 온 편지                                              | nan            | K             |
|  20228560 | 너와 나                                                       | nan            | K             |
|  20232077 | 어른 김장하                                                   | nan            | K             |
|  20233299 | 크레센도                                                      | Y              | F             |
|  20234114 | 괴물                                                          | Y              | F             |
|  20234664 | 그대들은 어떻게 살 것인가                                     | Y              | nan           |
|  20234673 | 뽀로로 극장판 슈퍼스타 대모험                                 | N              | K             |
|  20235098 | 나폴레옹                                                      | N              | nan           |
|  20235290 | 도티와 영원의 탑                                              | N              | K             |
|  20235596 | 트롤: 밴드 투게더                                             | N              | F             |
|  20235693 | 리빙: 어떤 인생                                               | Y              | F             |
|  20235697 | 엔시티 네이션 : 투 더 월드 인 시네마                          | nan            | K             |
|  20235735 | 아쿠아맨과 로스트 킹덤                                        | N              | F             |
|  20235923 | 사랑은 낙엽을 타고                                            | Y              | F             |
|  20235980 | 말하고 싶은 비밀                                              | N              | F             |
|  20236045 | 바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라! | Y              | F             |
|  20236080 | 류이치 사카모토: 오퍼스                                       | Y              | F             |
|  20236146 | 신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~ | N              | F             |
|  20236533 | 립세의 사계                                                   | Y              | nan           |

In [15]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 'movieCd'를 인덱스로 사용하여 그룹화 및 집계 수행
df_clean = df.groupby('movieCd').agg({
    'movieNm': first_non_null,
    'multiMovieYn': first_non_null,
    'repNationCd': first_non_null
})

# 결과 DataFrame을 인덱스 형식(기본 텍스트 출력)으로 출력
print(df_clean.to_string(index=True))

                                       movieNm multiMovieYn repNationCd
movieCd
19860125                                  쿼바디스            Y         NaN
20124722                             피아니스트의 전설            Y         NaN
20190324                                3일의 휴가            N           K
20202247                               싱글 인 서울          NaN           K
20203702                            노량: 죽음의 바다            N           K
20212866                                 서울의 봄            N           K
20227525                             교토에서 온 편지          NaN           K
20228560                                  너와 나          NaN           K
20232077                                어른 김장하          NaN           K
20233299                                  크레센도            Y           F
20234114                                    괴물            Y           F
20234664                        그대들은 어떻게 살 것인가            Y         NaN
20234673                      뽀로로 극장판 슈퍼스타 대모험            N           K
20235098                                  나폴레옹            N         NaN
20235290                             도티와 영원의 탑            N           K
20235596                            트롤: 밴드 투게더            N           F
20235693                             리빙: 어떤 인생            Y           F
20235697                엔시티 네이션 : 투 더 월드 인 시네마          NaN           K
20235735                          아쿠아맨과 로스트 킹덤            N           F
20235923                            사랑은 낙엽을 타고            Y           F
20235980                             말하고 싶은 비밀            N           F
20236045  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!            Y           F
20236080                         류이치 사카모토: 오퍼스            Y           F
20236146  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~            N           F
20236533                                립세의 사계            Y         NaN

In [16]:
# 예시로 사용할 get_counts 함수 (실제 로직에 맞게 수정하세요)
def get_counts(group, include_groups=False):
    # 예: 각 그룹의 행 수를 계산하여 'count' 컬럼에 저장하는 경우
    return pd.Series({'count': len(group)})

# df_grouped_nm 데이터프레임이 이미 존재한다고 가정합니다.
# movieNm을 기준으로 그룹화한 후 get_counts 함수를 적용하고, 인덱스를 재설정합니다.
result_df = df_grouped_nm.groupby('movieNm', group_keys=False) \
    .apply(get_counts, include_groups=False) \
    .reset_index()

# print() 함수를 사용하여 기본 출력 형식으로 결과 출력
print(result_df)

NameError: name 'df_grouped_nm' is not defined

In [17]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 'movieCd'를 인덱스로 사용하여 그룹화 및 집계 후, reset_index()를 적용
df_clean = df.groupby('movieCd').agg({
    'movieNm': first_non_null,
    'multiMovieYn': first_non_null,
    'repNationCd': first_non_null
}).reset_index()

# reset_index() 후의 결과 DataFrame을 마크다운 형식으로 출력
print(df_clean.to_markdown(index=False))

|   movieCd | movieNm                                                       | multiMovieYn   | repNationCd   |
|----------:|:--------------------------------------------------------------|:---------------|:--------------|
|  19860125 | 쿼바디스                                                      | Y              | nan           |
|  20124722 | 피아니스트의 전설                                             | Y              | nan           |
|  20190324 | 3일의 휴가                                                    | N              | K             |
|  20202247 | 싱글 인 서울                                                  | nan            | K             |
|  20203702 | 노량: 죽음의 바다                                             | N              | K             |
|  20212866 | 서울의 봄                                                     | N              | K             |
|  20227525 | 교토에서 온 편지                                              | nan            | K             |
|  20228560 | 너와 나                                                       | nan            | K             |
|  20232077 | 어른 김장하                                                   | nan            | K             |
|  20233299 | 크레센도                                                      | Y              | F             |
|  20234114 | 괴물                                                          | Y              | F             |
|  20234664 | 그대들은 어떻게 살 것인가                                     | Y              | nan           |
|  20234673 | 뽀로로 극장판 슈퍼스타 대모험                                 | N              | K             |
|  20235098 | 나폴레옹                                                      | N              | nan           |
|  20235290 | 도티와 영원의 탑                                              | N              | K             |
|  20235596 | 트롤: 밴드 투게더                                             | N              | F             |
|  20235693 | 리빙: 어떤 인생                                               | Y              | F             |
|  20235697 | 엔시티 네이션 : 투 더 월드 인 시네마                          | nan            | K             |
|  20235735 | 아쿠아맨과 로스트 킹덤                                        | N              | F             |
|  20235923 | 사랑은 낙엽을 타고                                            | Y              | F             |
|  20235980 | 말하고 싶은 비밀                                              | N              | F             |
|  20236045 | 바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라! | Y              | F             |
|  20236080 | 류이치 사카모토: 오퍼스                                       | Y              | F             |
|  20236146 | 신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~ | N              | F             |
|  20236533 | 립세의 사계                                                   | Y              | nan           |

In [18]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 'movieCd'를 인덱스로 사용하여 그룹화 및 집계 후 reset_index()를 적용
df_clean = df.groupby('movieCd').agg({
    'movieNm': first_non_null,
    'multiMovieYn': first_non_null,
    'repNationCd': first_non_null
}).reset_index()

# 결과 DataFrame을 기본 출력 형식 그대로 출력
print(df_clean)

     movieCd                               movieNm multiMovieYn repNationCd
0   19860125                                  쿼바디스            Y         NaN
1   20124722                             피아니스트의 전설            Y         NaN
2   20190324                                3일의 휴가            N           K
3   20202247                               싱글 인 서울          NaN           K
4   20203702                            노량: 죽음의 바다            N           K
5   20212866                                 서울의 봄            N           K
6   20227525                             교토에서 온 편지          NaN           K
7   20228560                                  너와 나          NaN           K
8   20232077                                어른 김장하          NaN           K
9   20233299                                  크레센도            Y           F
10  20234114                                    괴물            Y           F
11  20234664                        그대들은 어떻게 살 것인가            Y         NaN
12  20234673                      뽀로로 극장판 슈퍼스타 대모험            N           K
13  20235098                                  나폴레옹            N         NaN
14  20235290                             도티와 영원의 탑            N           K
15  20235596                            트롤: 밴드 투게더            N           F
16  20235693                             리빙: 어떤 인생            Y           F
17  20235697                엔시티 네이션 : 투 더 월드 인 시네마          NaN           K
18  20235735                          아쿠아맨과 로스트 킹덤            N           F
19  20235923                            사랑은 낙엽을 타고            Y           F
20  20235980                             말하고 싶은 비밀            N           F
21  20236045  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!            Y           F
22  20236080                         류이치 사카모토: 오퍼스            Y           F
23  20236146  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~            N           F
24  20236533                                립세의 사계            Y         NaN

In [19]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 'movieCd'를 인덱스로 사용하여 그룹화 및 집계 후 reset_index()를 적용
df_clean = df.groupby('movieCd').agg({
    'movieNm': first_non_null,
    'multiMovieYn': first_non_null,
    'repNationCd': first_non_null
}).reset_index()

# 1) 셀 마지막에 df_clean만 적어도 자동으로 예쁜 표로 출력됩니다.
df_clean

     movieCd                               movieNm multiMovieYn repNationCd
0   19860125                                  쿼바디스            Y         NaN
1   20124722                             피아니스트의 전설            Y         NaN
2   20190324                                3일의 휴가            N           K
3   20202247                               싱글 인 서울          NaN           K
4   20203702                            노량: 죽음의 바다            N           K
5   20212866                                 서울의 봄            N           K
6   20227525                             교토에서 온 편지          NaN           K
7   20228560                                  너와 나          NaN           K
8   20232077                                어른 김장하          NaN           K
9   20233299                                  크레센도            Y           F
10  20234114                                    괴물            Y           F
11  20234664                        그대들은 어떻게 살 것인가            Y         NaN
12  20234673                      뽀로로 극장판 슈퍼스타 대모험            N           K
13  20235098                                  나폴레옹            N         NaN
14  20235290                             도티와 영원의 탑            N           K
15  20235596                            트롤: 밴드 투게더            N           F
16  20235693                             리빙: 어떤 인생            Y           F
17  20235697                엔시티 네이션 : 투 더 월드 인 시네마          NaN           K
18  20235735                          아쿠아맨과 로스트 킹덤            N           F
19  20235923                            사랑은 낙엽을 타고            Y           F
20  20235980                             말하고 싶은 비밀            N           F
21  20236045  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!            Y           F
22  20236080                         류이치 사카모토: 오퍼스            Y           F
23  20236146  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~            N           F
24  20236533                                립세의 사계            Y         NaN

In [20]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 'movieCd'를 인덱스로 사용하여 그룹화 및 집계 후 reset_index()를 적용
df_clean = df.groupby('movieCd').agg({
    'movieNm': first_non_null,
    'multiMovieYn': first_non_null,
    'repNationCd': first_non_null
}).reset_index()

df_clean

     movieCd                               movieNm multiMovieYn repNationCd
0   19860125                                  쿼바디스            Y         NaN
1   20124722                             피아니스트의 전설            Y         NaN
2   20190324                                3일의 휴가            N           K
3   20202247                               싱글 인 서울          NaN           K
4   20203702                            노량: 죽음의 바다            N           K
5   20212866                                 서울의 봄            N           K
6   20227525                             교토에서 온 편지          NaN           K
7   20228560                                  너와 나          NaN           K
8   20232077                                어른 김장하          NaN           K
9   20233299                                  크레센도            Y           F
10  20234114                                    괴물            Y           F
11  20234664                        그대들은 어떻게 살 것인가            Y         NaN
12  20234673                      뽀로로 극장판 슈퍼스타 대모험            N           K
13  20235098                                  나폴레옹            N         NaN
14  20235290                             도티와 영원의 탑            N           K
15  20235596                            트롤: 밴드 투게더            N           F
16  20235693                             리빙: 어떤 인생            Y           F
17  20235697                엔시티 네이션 : 투 더 월드 인 시네마          NaN           K
18  20235735                          아쿠아맨과 로스트 킹덤            N           F
19  20235923                            사랑은 낙엽을 타고            Y           F
20  20235980                             말하고 싶은 비밀            N           F
21  20236045  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!            Y           F
22  20236080                         류이치 사카모토: 오퍼스            Y           F
23  20236146  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~            N           F
24  20236533                                립세의 사계            Y         NaN

In [21]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 'movieCd'를 기준으로 그룹화하여, movieNm, multiMovieYn, repNationCd 컬럼에 대해 집계 수행
df_clean = df.groupby('movieCd', as_index=False).agg({
    'openDt': first_non_null,
    'movieNm': first_non_null,
    'multiMovieYn': first_non_null,
    'repNationCd': first_non_null
})
df_clean

,movieCd,openDt,movieNm,multiMovieYn,repNationCd
0,19860125,1973-01-13,쿼바디스,Y,NaN
1,20124722,2020-01-01,피아니스트의 전설,Y,NaN
2,20190324,2023-12-06,3일의 휴가,N,K
3,20202247,2023-11-29,싱글 인 서울,NaN,K
4,20203702,2023-12-20,노량: 죽음의 바다,N,K
5,20212866,2023-11-22,서울의 봄,N,K
6,20227525,2023-12-06,교토에서 온 편지,NaN,K
7,20228560,2023-10-25,너와 나,NaN,K
8,20232077,2023-11-15,어른 김장하,NaN,K
9,20233299,2023-12-20,크레센도,Y,F
10,20234114,2023-11-29,괴물,Y,F
11,20234664,2023-10-25,그대들은 어떻게 살 것인가,Y,NaN
12,20234673,2023-12-13,뽀로로 극장판 슈퍼스타 대모험,N,K
13,20235098,2023-12-06,나폴레옹,N,NaN
14,20235290,2023-12-27,도티와 영원의 탑,N,K
15,20235596,2023-12-20,트롤: 밴드 투게더,N,F
16,20235693,2023-12-13,리빙: 어떤 인생,Y,F
17,20235697,2023-12-06,엔시티 네이션 : 투 더 월드 인 시네마,NaN,K
18,20235735,2023-12-20,아쿠아맨과 로스트 킹덤,N,F
19,20235923,2023-12-20,사랑은 낙엽을 타고,Y,F
20,20235980,2023-12-13,말하고 싶은 비밀,N,F
21,20236045,2023-12-27,"바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!",Y,F
22,20236080,2023-12-27,류이치 사카모토: 오퍼스,Y,F
23,20236146,2023-12-22,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,N,F
24,20236533,2024-01-10,립세의 사계,Y,NaN

In [24]:
unique_movie_codes = df['movieCd'].unique()
print(unique_movie_codes)
print(len(unique_movie_codes))

['20203702' '20212866' '20236146' '20235735' '20235596' '20234673'
 '20235290' '20234114' '20236045' '20235980' '20190324' '20235098'
 '20236080' '20233299' '20235923' '20235693' '20234664' '20124722'
 '20236533' '19860125' '20202247' '20228560' '20235697' '20232077'
 '20227525']
25

In [27]:
# 2-1. multiMovieYn 컬럼의 NaN 건수
nan_multiMovieYn = df['multiMovieYn'].isna().sum()

# 2-2. repNationCd 컬럼의 NaN 건수
nan_repNationCd = df['repNationCd'].isna().sum()

# 2-3. multiMovieYn 과 repNationCd 두 컬럼이 동시에 NaN인 건수
nan_both = df[df['multiMovieYn'].isna() & df['repNationCd'].isna()].shape[0]

print("multiMovieYn의 NaN 건수:", nan_multiMovieYn)
print("repNationCd의 NaN 건수:", nan_repNationCd)
print("multiMovieYn과 repNationCd가 동시에 NaN인 건수:", nan_both)

multiMovieYn의 NaN 건수: 30
repNationCd의 NaN 건수: 30
multiMovieYn과 repNationCd가 동시에 NaN인 건수: 10

In [28]:
print(df)

    rnum  rank  rankInten rankOldAndNew   movieCd  \
0      1     1          0           OLD  20203702
1      2     2          0           OLD  20212866
2      3     3          0           OLD  20236146
3      4     4          0           OLD  20235735
4      5     5          0           OLD  20235596
5      6     6          1           OLD  20234673
6      7     7         -1           OLD  20235290
7      8     8          0           OLD  20234114
8      9     9          0           OLD  20236045
9     10    10          1           OLD  20235980
10     1     1          0           OLD  20203702
11     2     2          0           OLD  20212866
12     3     3          0           OLD  20236146
13     4     4          0           OLD  20235735
14     5     5          0           OLD  20235596
15     6     6          1           OLD  20234673
16     7     7         -1           OLD  20235290
17     8     8          0           OLD  20235980
18     9     9          0           OLD  20190324
19    10    10          0           OLD  20235098
20     1     1          0           OLD  20234114
21     2     2          0           OLD  20236045
22     3     3          0           OLD  20236080
23     4     4          0           OLD  20233299
24     5     5          0           OLD  20235923
25     6     6          0           OLD  20235693
26     7     7          5           OLD  20234664
27     8     8          2           OLD  20124722
28     9     8          0           NEW  20236533
29    10    10          4           OLD  19860125
30     1     1          0           OLD  20236146
31     2     2          0           OLD  20235735
32     3     3          0           OLD  20235596
33     4     4          0           OLD  20234114
34     5     5          0           OLD  20236045
35     6     6          1           OLD  20235980
36     7     7         -1           OLD  20236080
37     8     8          0           OLD  20233299
38     9     9          0           OLD  20235923
39    10    10          0           OLD  20235693
40     1     1          0           OLD  20203702
41     2     2          0           OLD  20212866
42     3     3          1           OLD  20234673
43     4     4         -1           OLD  20235290
44     5     5          0           OLD  20190324
45     6     6          2           OLD  20202247
46     7     7         -1           OLD  20228560
47     8     8          1           OLD  20235697
48     9     9          6           OLD  20232077
49    10    10          3           OLD  20227525

                                 movieNm      openDt    salesAmt  salesShare  \
0                             노량: 죽음의 바다  2023-12-20  2893509165        38.8
1                                  서울의 봄  2023-11-22  2666429137        35.8
2   신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~  2023-12-22   565417320         7.6
3                           아쿠아맨과 로스트 킹덤  2023-12-20   507984981         6.8
4                             트롤: 밴드 투게더  2023-12-20   273538754         3.7
5                       뽀로로 극장판 슈퍼스타 대모험  2023-12-13   113680587         1.5
6                              도티와 영원의 탑  2023-12-27   100024717         1.3
7                                     괴물  2023-11-29    92381680         1.2
8   바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!  2023-12-27    53094530         0.7
9                              말하고 싶은 비밀  2023-12-13    38025184         0.5
10                            노량: 죽음의 바다  2023-12-20  2893509165        40.2
11                                 서울의 봄  2023-11-22  2666429137        37.0
12  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~  2023-12-22   565417320         7.8
13                          아쿠아맨과 로스트 킹덤  2023-12-20   507984981         7.1
14                            트롤: 밴드 투게더  2023-12-20   273538754         3.8
15                      뽀로로 극장판 슈퍼스타 대모험  2023-12-13   113680587         1.6
16                             도티와 영원의 탑  2023-12-27   100024717         1.4
17                             말하고 싶은 비밀  2023-12-13    38025184         0.5
18                                3일의 휴가  2023-12-06    28109697         0.4
19                                  나폴레옹  2023-12-06     4056567         0.1
20                                    괴물  2023-11-29    92381680        37.0
21  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!  2023-12-27    53094530        21.3
22                         류이치 사카모토: 오퍼스  2023-12-27    31686950        12.7
23                                  크레센도  2023-12-20    29203100        11.7
24                            사랑은 낙엽을 타고  2023-12-20    11011634         4.4
25                             리빙: 어떤 인생  2023-12-13     6942434         2.8
26                        그대들은 어떻게 살 것인가  2023-10-25     3371362         1.4
27                             피아니스트의 전설  2020-01-01     3063078         1.2
28                                립세의 사계  2024-01-10     2804970         1.1
29                                  쿼바디스  1973-01-13      589000         0.2
30  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~  2023-12-22   565417320        34.4
31                          아쿠아맨과 로스트 킹덤  2023-12-20   507984981        30.9
32                            트롤: 밴드 투게더  2023-12-20   273538754        16.6
33                                    괴물  2023-11-29    92381680         5.6
34  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!  2023-12-27    53094530         3.2
35                             말하고 싶은 비밀  2023-12-13    38025184         2.3
36                         류이치 사카모토: 오퍼스  2023-12-27    31686950         1.9
37                                  크레센도  2023-12-20    29203100         1.8
38                            사랑은 낙엽을 타고  2023-12-20    11011634         0.7
39                             리빙: 어떤 인생  2023-12-13     6942434         0.4
40                            노량: 죽음의 바다  2023-12-20  2893509165        49.8
41                                 서울의 봄  2023-11-22  2666429137        45.9
42                      뽀로로 극장판 슈퍼스타 대모험  2023-12-13   113680587         2.0
43                             도티와 영원의 탑  2023-12-27   100024717         1.7
44                                3일의 휴가  2023-12-06    28109697         0.5
45                               싱글 인 서울  2023-11-29     1903007         0.0
46                                  너와 나  2023-10-25     2625839         0.0
47                엔시티 네이션 : 투 더 월드 인 시네마  2023-12-06     1364000         0.0
48                                어른 김장하  2023-11-15      214000         0.0
49                             교토에서 온 편지  2023-12-06      207000         0.0

    salesInten  salesChange      salesAcc  audiCnt  audiInten  audiChange  \
0   -686119312        -19.2   36926118105   290717     -59184       -16.9
1   -649456909        -19.6  118016920547   262422     -64054       -19.6
2    -69888800        -11.0    6071745009    58239      -6751       -10.4
3   -156026099        -23.5    7967584753    49368     -14686       -22.9
4    -16945147         -5.8    3383181955    28988      -1952        -6.3
5      2278496          2.0    3046919883    11586        190         1.7
6    -13487835        -11.9     488186693    10704      -1268       -10.6
7     -3768994         -3.9    3884333955     8710       -524        -5.7
8      -707720         -1.3     372974290     6471         67         1.0
9     -2349427         -5.8     868379725     3765       -164        -4.2
10  -686119312        -19.2   36926118105   290717     -59184       -16.9
11  -649456909        -19.6  118016920547   262422     -64054       -19.6
12   -69888800        -11.0    6071745009    58239      -6751       -10.4
13  -156026099        -23.5    7967584753    49368     -14686       -22.9
14   -16945147         -5.8    3383181955    28988      -1952        -6.3
15     2278496          2.0    3046919883    11586        190         1.7
16   -13487835        -11.9     488186693    10704      -1268       -10.6
17    -2349427         -5.8     868379725     3765       -164        -4.2
18    -5429437        -16.2    4863180386     3295       -626       -16.0
19      -89539         -2.2    2246030517      540        -20        -3.6
20    -3768994         -3.9    3884333955     8710       -524        -5.7
21     -707720         -1.3     372974290     6471         67         1.0
22   -15234118        -32.5     317887981     3001      -1659       -35.6
23    -2644200         -8.3     424298400     2534       -235        -8.5
24      285955          2.7     163391820     1052        -28        -2.6
25    -1569966        -18.4     174717087      729       -181       -19.9
26     -142718         -4.1   19543638004      318        -29        -8.4
27    -1092200        -26.3     416989591      294       -142       -32.6
28     2804970        100.0       4330970      294        294       100.0
29      149000         33.9      37856982      292         72        32.7
30   -69888800        -11.0    6071745009    58239      -6751       -10.4
31  -156026099        -23.5    7967584753    49368     -14686       -22.9
32   -16945147         -5.8    3383181955    28988      -1952        -6.3
33    -3768994         -3.9    3884333955     8710       -524        -5.7
34     -707720         -1.3     372974290     6471         67         1.0
35    -2349427         -5.8     868379725     3765       -164        -4.2
36   -15234118        -32.5     317887981     3001      -1659       -35.6
37    -2644200         -8.3     424298400     2534       -235        -8.5
38      285955          2.7     163391820     1052        -28        -2.6
39    -1569966        -18.4     174717087      729       -181       -19.9
40  -686119312        -19.2   36926118105   290717     -59184       -16.9
41  -649456909        -19.6  118016920547   262422     -64054       -19.6
42     2278496          2.0    3046919883    11586        190         1.7
43   -13487835        -11.9     488186693    10704      -1268       -10.6
44    -5429437        -16.2    4863180386     3295       -626       -16.0
45     -409621        -17.7    3740536035      212        -17        -7.4
46    -3233861        -55.2     330224803      192       -337       -63.7
47    -3168000        -69.9     554784000       69       -144       -67.6
48      -58000        -21.3     230592472       31         -8       -20.5
49      -67800        -24.7      58288197       29        -19       -39.6

     audiAcc  scrnCnt  showCnt multiMovieYn repNationCd
0    3728850     1706     5793          NaN         NaN
1   12117201     1614     5444          NaN         NaN
2     626508      834     1671          NaN         NaN
3     772354      832     1611          NaN         NaN
4     365927      660      981          NaN         NaN
5     332776      335      432          NaN         NaN
6      52400      357      419          NaN         NaN
7     396137      187      263          NaN         NaN
8      45294      207      248          NaN         NaN
9      89597       95      127          NaN         NaN
10   3728850     1706     5793            N         NaN
11  12117201     1614     5444            N         NaN
12    626508      834     1671            N         NaN
13    772354      832     1611            N         NaN
14    365927      660      981            N         NaN
15    332776      335      432            N         NaN
16     52400      357      419            N         NaN
17     89597       95      127            N         NaN
18    517836      132      157            N         NaN
19    225912       23       25            N         NaN
20    396137      187      263            Y         NaN
21     45294      207      248            Y         NaN
22     34196      200      270            Y         NaN
23     39445       79      102            Y         NaN
24     17008       30       33            Y         NaN
25     18551       20       23            Y         NaN
26   2009716       17       20            Y         NaN
27     51876       23       25            Y         NaN
28       512        4        4            Y         NaN
29     20951        1        3            Y         NaN
30    626508      834     1671          NaN           F
31    772354      832     1611          NaN           F
32    365927      660      981          NaN           F
33    396137      187      263          NaN           F
34     45294      207      248          NaN           F
35     89597       95      127          NaN           F
36     34196      200      270          NaN           F
37     39445       79      102          NaN           F
38     17008       30       33          NaN           F
39     18551       20       23          NaN           F
40   3728850     1706     5793          NaN           K
41  12117201     1614     5444          NaN           K
42    332776      335      432          NaN           K
43     52400      357      419          NaN           K
44    517836      132      157          NaN           K
45    399787        9        9          NaN           K
46     33811        8        8          NaN           K
47     25099        8        8          NaN           K
48     27603        2        2          NaN           K
49      6717        3        3          NaN           K

In [29]:
import pandas as pd

# 1) audiCnt 기준 내림차순 정렬 후, movieCd 중복 제거(가장 큰 audiCnt 행만 남김)
df_unique = (
    df.sort_values('audiCnt', ascending=False)
      .drop_duplicates(subset='movieCd', keep='first')
      .reset_index(drop=True)
)

# 2) 기존 rnum, rank 컬럼 제거
df_unique.drop(columns=['rnum', 'rank'], inplace=True)

# 3) audiCnt 내림차순 순서에 따라 새 rnum, rank 컬럼 생성
#    (위에서부터 1, 2, 3... 순으로 매깁니다)
df_unique['rnum'] = df_unique.index + 1
df_unique['rank'] = df_unique.index + 1

# 결과 확인
print(df_unique)

    rankInten rankOldAndNew   movieCd                               movieNm  \
0           0           OLD  20203702                            노량: 죽음의 바다
1           0           OLD  20212866                                 서울의 봄
2           0           OLD  20236146  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~
3           0           OLD  20235735                          아쿠아맨과 로스트 킹덤
4           0           OLD  20235596                            트롤: 밴드 투게더
5           1           OLD  20234673                      뽀로로 극장판 슈퍼스타 대모험
6          -1           OLD  20235290                             도티와 영원의 탑
7           0           OLD  20234114                                    괴물
8           0           OLD  20236045  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!
9           1           OLD  20235980                             말하고 싶은 비밀
10          0           OLD  20190324                                3일의 휴가
11         -1           OLD  20236080                         류이치 사카모토: 오퍼스
12          0           OLD  20233299                                  크레센도
13          0           OLD  20235923                            사랑은 낙엽을 타고
14          0           OLD  20235693                             리빙: 어떤 인생
15          0           OLD  20235098                                  나폴레옹
16          5           OLD  20234664                        그대들은 어떻게 살 것인가
17          2           OLD  20124722                             피아니스트의 전설
18          0           NEW  20236533                                립세의 사계
19          4           OLD  19860125                                  쿼바디스
20          2           OLD  20202247                               싱글 인 서울
21         -1           OLD  20228560                                  너와 나
22          1           OLD  20235697                엔시티 네이션 : 투 더 월드 인 시네마
23          6           OLD  20232077                                어른 김장하
24          3           OLD  20227525                             교토에서 온 편지

        openDt    salesAmt  salesShare  salesInten  salesChange      salesAcc  \
0   2023-12-20  2893509165        38.8  -686119312        -19.2   36926118105
1   2023-11-22  2666429137        35.8  -649456909        -19.6  118016920547
2   2023-12-22   565417320         7.6   -69888800        -11.0    6071745009
3   2023-12-20   507984981         7.1  -156026099        -23.5    7967584753
4   2023-12-20   273538754         3.7   -16945147         -5.8    3383181955
5   2023-12-13   113680587         1.5     2278496          2.0    3046919883
6   2023-12-27   100024717         1.3   -13487835        -11.9     488186693
7   2023-11-29    92381680         1.2    -3768994         -3.9    3884333955
8   2023-12-27    53094530         0.7     -707720         -1.3     372974290
9   2023-12-13    38025184         0.5    -2349427         -5.8     868379725
10  2023-12-06    28109697         0.4    -5429437        -16.2    4863180386
11  2023-12-27    31686950         1.9   -15234118        -32.5     317887981
12  2023-12-20    29203100         1.8    -2644200         -8.3     424298400
13  2023-12-20    11011634         4.4      285955          2.7     163391820
14  2023-12-13     6942434         0.4    -1569966        -18.4     174717087
15  2023-12-06     4056567         0.1      -89539         -2.2    2246030517
16  2023-10-25     3371362         1.4     -142718         -4.1   19543638004
17  2020-01-01     3063078         1.2    -1092200        -26.3     416989591
18  2024-01-10     2804970         1.1     2804970        100.0       4330970
19  1973-01-13      589000         0.2      149000         33.9      37856982
20  2023-11-29     1903007         0.0     -409621        -17.7    3740536035
21  2023-10-25     2625839         0.0    -3233861        -55.2     330224803
22  2023-12-06     1364000         0.0    -3168000        -69.9     554784000
23  2023-11-15      214000         0.0      -58000        -21.3     230592472
24  2023-12-06      207000         0.0      -67800        -24.7      58288197

    audiCnt  audiInten  audiChange   audiAcc  scrnCnt  showCnt multiMovieYn  \
0    290717     -59184       -16.9   3728850     1706     5793          NaN
1    262422     -64054       -19.6  12117201     1614     5444          NaN
2     58239      -6751       -10.4    626508      834     1671          NaN
3     49368     -14686       -22.9    772354      832     1611            N
4     28988      -1952        -6.3    365927      660      981          NaN
5     11586        190         1.7    332776      335      432          NaN
6     10704      -1268       -10.6     52400      357      419          NaN
7      8710       -524        -5.7    396137      187      263          NaN
8      6471         67         1.0     45294      207      248          NaN
9      3765       -164        -4.2     89597       95      127          NaN
10     3295       -626       -16.0    517836      132      157            N
11     3001      -1659       -35.6     34196      200      270          NaN
12     2534       -235        -8.5     39445       79      102          NaN
13     1052        -28        -2.6     17008       30       33            Y
14      729       -181       -19.9     18551       20       23          NaN
15      540        -20        -3.6    225912       23       25            N
16      318        -29        -8.4   2009716       17       20            Y
17      294       -142       -32.6     51876       23       25            Y
18      294        294       100.0       512        4        4            Y
19      292         72        32.7     20951        1        3            Y
20      212        -17        -7.4    399787        9        9          NaN
21      192       -337       -63.7     33811        8        8          NaN
22       69       -144       -67.6     25099        8        8          NaN
23       31         -8       -20.5     27603        2        2          NaN
24       29        -19       -39.6      6717        3        3          NaN

   repNationCd  rnum  rank
0          NaN     1     1
1          NaN     2     2
2          NaN     3     3
3          NaN     4     4
4          NaN     5     5
5          NaN     6     6
6          NaN     7     7
7          NaN     8     8
8          NaN     9     9
9          NaN    10    10
10         NaN    11    11
11           F    12    12
12           F    13    13
13         NaN    14    14
14           F    15    15
15         NaN    16    16
16         NaN    17    17
17         NaN    18    18
18         NaN    19    19
19         NaN    20    20
20           K    21    21
21           K    22    22
22           K    23    23
23           K    24    24
24           K    25    25

In [30]:
import pandas as pd

# 1) audiCnt 기준 내림차순 정렬 후, movieCd 중복 제거(가장 큰 audiCnt 행만 남김)
df_unique = (
    df.sort_values('audiCnt', ascending=False)
      .drop_duplicates(subset='movieCd', keep='first')
      .reset_index(drop=True)
)

# 2) 기존 rnum, rank 컬럼 제거 (존재하지 않더라도 에러 무시)
df_unique.drop(columns=['rnum', 'rank'], errors='ignore', inplace=True)

# 3) 새 rnum, rank 컬럼 생성 (1부터 시작)
df_unique['rnum'] = df_unique.index + 1
df_unique['rank'] = df_unique.index + 1

# 4) 원하는 컬럼만 지정한 순서대로 추출
df_result = df_unique[['movieCd', 'movieNm', 'openDt', 'rnum', 'rank']]

# 결과 출력
print(df_result)

     movieCd                               movieNm      openDt  rnum  rank
0   20203702                            노량: 죽음의 바다  2023-12-20     1     1
1   20212866                                 서울의 봄  2023-11-22     2     2
2   20236146  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~  2023-12-22     3     3
3   20235735                          아쿠아맨과 로스트 킹덤  2023-12-20     4     4
4   20235596                            트롤: 밴드 투게더  2023-12-20     5     5
5   20234673                      뽀로로 극장판 슈퍼스타 대모험  2023-12-13     6     6
6   20235290                             도티와 영원의 탑  2023-12-27     7     7
7   20234114                                    괴물  2023-11-29     8     8
8   20236045  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!  2023-12-27     9     9
9   20235980                             말하고 싶은 비밀  2023-12-13    10    10
10  20190324                                3일의 휴가  2023-12-06    11    11
11  20236080                         류이치 사카모토: 오퍼스  2023-12-27    12    12
12  20233299                                  크레센도  2023-12-20    13    13
13  20235923                            사랑은 낙엽을 타고  2023-12-20    14    14
14  20235693                             리빙: 어떤 인생  2023-12-13    15    15
15  20235098                                  나폴레옹  2023-12-06    16    16
16  20234664                        그대들은 어떻게 살 것인가  2023-10-25    17    17
17  20124722                             피아니스트의 전설  2020-01-01    18    18
18  20236533                                립세의 사계  2024-01-10    19    19
19  19860125                                  쿼바디스  1973-01-13    20    20
20  20202247                               싱글 인 서울  2023-11-29    21    21
21  20228560                                  너와 나  2023-10-25    22    22
22  20235697                엔시티 네이션 : 투 더 월드 인 시네마  2023-12-06    23    23
23  20232077                                어른 김장하  2023-11-15    24    24
24  20227525                             교토에서 온 편지  2023-12-06    25    25

In [31]:
import pandas as pd

# 1) audiCnt 기준 내림차순 정렬 후, movieCd 중복 제거 (가장 큰 audiCnt 행만 남김)
df_unique = (
    df.sort_values('audiCnt', ascending=False)
      .drop_duplicates(subset='movieCd', keep='first')
      .reset_index(drop=True)
)

# 2) 기존 rnum, rank 컬럼 제거 (존재하지 않아도 에러 무시)
df_unique.drop(columns=['rnum', 'rank'], errors='ignore', inplace=True)

# 3) 새 rnum, rank 컬럼 생성 (1부터 시작)
df_unique['rnum'] = df_unique.index + 1
df_unique['rank'] = df_unique.index + 1

# 4) 원하는 컬럼만 지정한 순서대로 추출
df_result = df_unique[['movieCd', 'movieNm', 'openDt', 'rnum', 'rank']]

# 5) 결과 DataFrame을 마크다운 형식으로 출력
print(df_result.to_markdown(index=False))

|   movieCd | movieNm                                                       | openDt     |   rnum |   rank |
|----------:|:--------------------------------------------------------------|:-----------|-------:|-------:|
|  20203702 | 노량: 죽음의 바다                                             | 2023-12-20 |      1 |      1 |
|  20212866 | 서울의 봄                                                     | 2023-11-22 |      2 |      2 |
|  20236146 | 신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~ | 2023-12-22 |      3 |      3 |
|  20235735 | 아쿠아맨과 로스트 킹덤                                        | 2023-12-20 |      4 |      4 |
|  20235596 | 트롤: 밴드 투게더                                             | 2023-12-20 |      5 |      5 |
|  20234673 | 뽀로로 극장판 슈퍼스타 대모험                                 | 2023-12-13 |      6 |      6 |
|  20235290 | 도티와 영원의 탑                                              | 2023-12-27 |      7 |      7 |
|  20234114 | 괴물                                                          | 2023-11-29 |      8 |      8 |
|  20236045 | 바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라! | 2023-12-27 |      9 |      9 |
|  20235980 | 말하고 싶은 비밀                                              | 2023-12-13 |     10 |     10 |
|  20190324 | 3일의 휴가                                                    | 2023-12-06 |     11 |     11 |
|  20236080 | 류이치 사카모토: 오퍼스                                       | 2023-12-27 |     12 |     12 |
|  20233299 | 크레센도                                                      | 2023-12-20 |     13 |     13 |
|  20235923 | 사랑은 낙엽을 타고                                            | 2023-12-20 |     14 |     14 |
|  20235693 | 리빙: 어떤 인생                                               | 2023-12-13 |     15 |     15 |
|  20235098 | 나폴레옹                                                      | 2023-12-06 |     16 |     16 |
|  20234664 | 그대들은 어떻게 살 것인가                                     | 2023-10-25 |     17 |     17 |
|  20124722 | 피아니스트의 전설                                             | 2020-01-01 |     18 |     18 |
|  20236533 | 립세의 사계                                                   | 2024-01-10 |     19 |     19 |
|  19860125 | 쿼바디스                                                      | 1973-01-13 |     20 |     20 |
|  20202247 | 싱글 인 서울                                                  | 2023-11-29 |     21 |     21 |
|  20228560 | 너와 나                                                       | 2023-10-25 |     22 |     22 |
|  20235697 | 엔시티 네이션 : 투 더 월드 인 시네마                          | 2023-12-06 |     23 |     23 |
|  20232077 | 어른 김장하                                                   | 2023-11-15 |     24 |     24 |
|  20227525 | 교토에서 온 편지                                              | 2023-12-06 |     25 |     25 |

In [32]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 1) audiCnt 기준 내림차순 정렬 후, movieCd 중복 제거 (가장 큰 audiCnt 행만 남김)
df_unique = (
    df.sort_values('audiCnt', ascending=False)
      .drop_duplicates(subset='movieCd', keep='first')
      .reset_index(drop=True)
)

# 2) 기존 rnum, rank 컬럼 제거 (존재하지 않아도 에러 무시)
df_unique.drop(columns=['rnum', 'rank'], errors='ignore', inplace=True)

# 3) 새 rnum, rank 컬럼 생성 (1부터 시작)
df_unique['rnum'] = df_unique.index + 1
df_unique['rank'] = df_unique.index + 1

# 4) 원하는 컬럼만 지정한 순서대로 추출: movieCd, movieNm, openDt, rnum, rank
df_result = df_unique[['movieCd', 'movieNm', 'openDt', 'rnum', 'rank']]

# 전체 결과를 마크다운 형식으로 출력
print("전체 결과:")
print(df_result.to_markdown(index=False))

# head 3 출력
print("\nHead 3:")
print(df_result.head(3).to_markdown(index=False))

# tail 3 출력
print("\nTail 3:")
print(df_result.tail(3).to_markdown(index=False))

# 'movieCd' 컬럼만 별도로 출력 (DataFrame 형태로 변환하여 마크다운 출력)
print("\n'movieCd' 컬럼:")
print(df_result[['movieCd']].to_markdown(index=False))

전체 결과:
|   movieCd | movieNm                                                       | openDt     |   rnum |   rank |
|----------:|:--------------------------------------------------------------|:-----------|-------:|-------:|
|  20203702 | 노량: 죽음의 바다                                             | 2023-12-20 |      1 |      1 |
|  20212866 | 서울의 봄                                                     | 2023-11-22 |      2 |      2 |
|  20236146 | 신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~ | 2023-12-22 |      3 |      3 |
|  20235735 | 아쿠아맨과 로스트 킹덤                                        | 2023-12-20 |      4 |      4 |
|  20235596 | 트롤: 밴드 투게더                                             | 2023-12-20 |      5 |      5 |
|  20234673 | 뽀로로 극장판 슈퍼스타 대모험                                 | 2023-12-13 |      6 |      6 |
|  20235290 | 도티와 영원의 탑                                              | 2023-12-27 |      7 |      7 |
|  20234114 | 괴물                                                          | 2023-11-29 |      8 |      8 |
|  20236045 | 바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라! | 2023-12-27 |      9 |      9 |
|  20235980 | 말하고 싶은 비밀                                              | 2023-12-13 |     10 |     10 |
|  20190324 | 3일의 휴가                                                    | 2023-12-06 |     11 |     11 |
|  20236080 | 류이치 사카모토: 오퍼스                                       | 2023-12-27 |     12 |     12 |
|  20233299 | 크레센도                                                      | 2023-12-20 |     13 |     13 |
|  20235923 | 사랑은 낙엽을 타고                                            | 2023-12-20 |     14 |     14 |
|  20235693 | 리빙: 어떤 인생                                               | 2023-12-13 |     15 |     15 |
|  20235098 | 나폴레옹                                                      | 2023-12-06 |     16 |     16 |
|  20234664 | 그대들은 어떻게 살 것인가                                     | 2023-10-25 |     17 |     17 |
|  20124722 | 피아니스트의 전설                                             | 2020-01-01 |     18 |     18 |
|  20236533 | 립세의 사계                                                   | 2024-01-10 |     19 |     19 |
|  19860125 | 쿼바디스                                                      | 1973-01-13 |     20 |     20 |
|  20202247 | 싱글 인 서울                                                  | 2023-11-29 |     21 |     21 |
|  20228560 | 너와 나                                                       | 2023-10-25 |     22 |     22 |
|  20235697 | 엔시티 네이션 : 투 더 월드 인 시네마                          | 2023-12-06 |     23 |     23 |
|  20232077 | 어른 김장하                                                   | 2023-11-15 |     24 |     24 |
|  20227525 | 교토에서 온 편지                                              | 2023-12-06 |     25 |     25 |

Head 3:
|   movieCd | movieNm                                                       | openDt     |   rnum |   rank |
|----------:|:--------------------------------------------------------------|:-----------|-------:|-------:|
|  20203702 | 노량: 죽음의 바다                                             | 2023-12-20 |      1 |      1 |
|  20212866 | 서울의 봄                                                     | 2023-11-22 |      2 |      2 |
|  20236146 | 신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~ | 2023-12-22 |      3 |      3 |

Tail 3:
|   movieCd | movieNm                              | openDt     |   rnum |   rank |
|----------:|:-------------------------------------|:-----------|-------:|-------:|
|  20235697 | 엔시티 네이션 : 투 더 월드 인 시네마 | 2023-12-06 |     23 |     23 |
|  20232077 | 어른 김장하                          | 2023-11-15 |     24 |     24 |
|  20227525 | 교토에서 온 편지                     | 2023-12-06 |     25 |     25 |

'movieCd' 컬럼:
|   movieCd |
|----------:|
|  20203702 |
|  20212866 |
|  20236146 |
|  20235735 |
|  20235596 |
|  20234673 |
|  20235290 |
|  20234114 |
|  20236045 |
|  20235980 |
|  20190324 |
|  20236080 |
|  20233299 |
|  20235923 |
|  20235693 |
|  20235098 |
|  20234664 |
|  20124722 |
|  20236533 |
|  19860125 |
|  20202247 |
|  20228560 |
|  20235697 |
|  20232077 |
|  20227525 |

In [37]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 1) audiCnt 기준 내림차순 정렬 후, movieCd 중복 제거 (가장 큰 audiCnt 행만 남김)
df_unique = (
    df.sort_values('audiCnt', ascending=False)
      .drop_duplicates(subset='movieCd', keep='first')
      .reset_index(drop=True)
)

# 2) 기존 rnum, rank 컬럼 제거 (존재하지 않아도 에러 무시)
df_unique.drop(columns=['rnum', 'rank'], errors='ignore', inplace=True)

# 3) 새 rnum, rank 컬럼 생성 (1부터 시작)
df_unique['rnum'] = df_unique.index + 1
df_unique['rank'] = df_unique.index + 1

# 4) 원하는 컬럼만 지정한 순서대로 추출: movieCd, movieNm, openDt, rnum, rank
df_result = df_unique[['movieCd', 'movieNm', 'openDt', 'audiCnt', 'rnum', 'rank']]

# 전체 결과를 마크다운 형식으로 출력
print("전체 결과:")
print(df_result.to_markdown(index=False))


# 상위 3개 행의 'movieNm' 컬럼만 출력
print("Head 3 (movieNm only):")
print(df_result[['movieNm']].head(3).to_markdown(index=False))

# 하위 3개 행의 'movieNm' 컬럼만 출력
print("\nTail 3 (movieNm only):")
print(df_result[['movieNm']].tail(3).to_markdown(index=False))

전체 결과:
|   movieCd | movieNm                                                       | openDt     |   audiCnt |   rnum |   rank |
|----------:|:--------------------------------------------------------------|:-----------|----------:|-------:|-------:|
|  20203702 | 노량: 죽음의 바다                                             | 2023-12-20 |    290717 |      1 |      1 |
|  20212866 | 서울의 봄                                                     | 2023-11-22 |    262422 |      2 |      2 |
|  20236146 | 신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~ | 2023-12-22 |     58239 |      3 |      3 |
|  20235735 | 아쿠아맨과 로스트 킹덤                                        | 2023-12-20 |     49368 |      4 |      4 |
|  20235596 | 트롤: 밴드 투게더                                             | 2023-12-20 |     28988 |      5 |      5 |
|  20234673 | 뽀로로 극장판 슈퍼스타 대모험                                 | 2023-12-13 |     11586 |      6 |      6 |
|  20235290 | 도티와 영원의 탑                                              | 2023-12-27 |     10704 |      7 |      7 |
|  20234114 | 괴물                                                          | 2023-11-29 |      8710 |      8 |      8 |
|  20236045 | 바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라! | 2023-12-27 |      6471 |      9 |      9 |
|  20235980 | 말하고 싶은 비밀                                              | 2023-12-13 |      3765 |     10 |     10 |
|  20190324 | 3일의 휴가                                                    | 2023-12-06 |      3295 |     11 |     11 |
|  20236080 | 류이치 사카모토: 오퍼스                                       | 2023-12-27 |      3001 |     12 |     12 |
|  20233299 | 크레센도                                                      | 2023-12-20 |      2534 |     13 |     13 |
|  20235923 | 사랑은 낙엽을 타고                                            | 2023-12-20 |      1052 |     14 |     14 |
|  20235693 | 리빙: 어떤 인생                                               | 2023-12-13 |       729 |     15 |     15 |
|  20235098 | 나폴레옹                                                      | 2023-12-06 |       540 |     16 |     16 |
|  20234664 | 그대들은 어떻게 살 것인가                                     | 2023-10-25 |       318 |     17 |     17 |
|  20124722 | 피아니스트의 전설                                             | 2020-01-01 |       294 |     18 |     18 |
|  20236533 | 립세의 사계                                                   | 2024-01-10 |       294 |     19 |     19 |
|  19860125 | 쿼바디스                                                      | 1973-01-13 |       292 |     20 |     20 |
|  20202247 | 싱글 인 서울                                                  | 2023-11-29 |       212 |     21 |     21 |
|  20228560 | 너와 나                                                       | 2023-10-25 |       192 |     22 |     22 |
|  20235697 | 엔시티 네이션 : 투 더 월드 인 시네마                          | 2023-12-06 |        69 |     23 |     23 |
|  20232077 | 어른 김장하                                                   | 2023-11-15 |        31 |     24 |     24 |
|  20227525 | 교토에서 온 편지                                              | 2023-12-06 |        29 |     25 |     25 |
Head 3 (movieNm only):
| movieNm                                                       |
|:--------------------------------------------------------------|
| 노량: 죽음의 바다                                             |
| 서울의 봄                                                     |
| 신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~ |

Tail 3 (movieNm only):
| movieNm                              |
|:-------------------------------------|
| 엔시티 네이션 : 투 더 월드 인 시네마 |
| 어른 김장하                          |
| 교토에서 온 편지                     |

In [38]:
import numpy as np
import pandas as pd

# NaN이 아닌 첫 번째 값을 반환하는 함수 정의
def first_non_null(series):
    valid = series.dropna()
    return valid.iloc[0] if len(valid) > 0 else np.nan

# 1) audiCnt 기준 내림차순 정렬 후, movieCd 중복 제거 (가장 큰 audiCnt 행만 남김)
df_unique = (
    df.sort_values('audiCnt', ascending=False)
      .drop_duplicates(subset='movieCd', keep='first')
      .reset_index(drop=True)
)

# 2) 기존 rnum, rank 컬럼 제거 (존재하지 않아도 에러 무시)
df_unique.drop(columns=['rnum', 'rank'], errors='ignore', inplace=True)

# 3) 새 rnum, rank 컬럼 생성 (1부터 시작)
df_unique['rnum'] = df_unique.index + 1
df_unique['rank'] = df_unique.index + 1

# 4) 원하는 컬럼만 지정한 순서대로 추출: movieCd, movieNm, openDt, rnum, rank
df_result = df_unique[['movieCd', 'movieNm', 'openDt', 'audiCnt', 'rnum', 'rank']]

# 전체 결과를 마크다운 형식으로 출력
print("전체 결과:")
print(df_result.to_markdown(index=False))

# head 3 출력
print("\nHead 3:")
print(df_result.head(3).to_markdown(index=False))

# tail 3 출력
print("\nTail 3:")
print(df_result.tail(3).to_markdown(index=False))

전체 결과:
|   movieCd | movieNm                                                       | openDt     |   audiCnt |   rnum |   rank |
|----------:|:--------------------------------------------------------------|:-----------|----------:|-------:|-------:|
|  20203702 | 노량: 죽음의 바다                                             | 2023-12-20 |    290717 |      1 |      1 |
|  20212866 | 서울의 봄                                                     | 2023-11-22 |    262422 |      2 |      2 |
|  20236146 | 신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~ | 2023-12-22 |     58239 |      3 |      3 |
|  20235735 | 아쿠아맨과 로스트 킹덤                                        | 2023-12-20 |     49368 |      4 |      4 |
|  20235596 | 트롤: 밴드 투게더                                             | 2023-12-20 |     28988 |      5 |      5 |
|  20234673 | 뽀로로 극장판 슈퍼스타 대모험                                 | 2023-12-13 |     11586 |      6 |      6 |
|  20235290 | 도티와 영원의 탑                                              | 2023-12-27 |     10704 |      7 |      7 |
|  20234114 | 괴물                                                          | 2023-11-29 |      8710 |      8 |      8 |
|  20236045 | 바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라! | 2023-12-27 |      6471 |      9 |      9 |
|  20235980 | 말하고 싶은 비밀                                              | 2023-12-13 |      3765 |     10 |     10 |
|  20190324 | 3일의 휴가                                                    | 2023-12-06 |      3295 |     11 |     11 |
|  20236080 | 류이치 사카모토: 오퍼스                                       | 2023-12-27 |      3001 |     12 |     12 |
|  20233299 | 크레센도                                                      | 2023-12-20 |      2534 |     13 |     13 |
|  20235923 | 사랑은 낙엽을 타고                                            | 2023-12-20 |      1052 |     14 |     14 |
|  20235693 | 리빙: 어떤 인생                                               | 2023-12-13 |       729 |     15 |     15 |
|  20235098 | 나폴레옹                                                      | 2023-12-06 |       540 |     16 |     16 |
|  20234664 | 그대들은 어떻게 살 것인가                                     | 2023-10-25 |       318 |     17 |     17 |
|  20124722 | 피아니스트의 전설                                             | 2020-01-01 |       294 |     18 |     18 |
|  20236533 | 립세의 사계                                                   | 2024-01-10 |       294 |     19 |     19 |
|  19860125 | 쿼바디스                                                      | 1973-01-13 |       292 |     20 |     20 |
|  20202247 | 싱글 인 서울                                                  | 2023-11-29 |       212 |     21 |     21 |
|  20228560 | 너와 나                                                       | 2023-10-25 |       192 |     22 |     22 |
|  20235697 | 엔시티 네이션 : 투 더 월드 인 시네마                          | 2023-12-06 |        69 |     23 |     23 |
|  20232077 | 어른 김장하                                                   | 2023-11-15 |        31 |     24 |     24 |
|  20227525 | 교토에서 온 편지                                              | 2023-12-06 |        29 |     25 |     25 |

Head 3:
|   movieCd | movieNm                                                       | openDt     |   audiCnt |   rnum |   rank |
|----------:|:--------------------------------------------------------------|:-----------|----------:|-------:|-------:|
|  20203702 | 노량: 죽음의 바다                                             | 2023-12-20 |    290717 |      1 |      1 |
|  20212866 | 서울의 봄                                                     | 2023-11-22 |    262422 |      2 |      2 |
|  20236146 | 신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~ | 2023-12-22 |     58239 |      3 |      3 |

Tail 3:
|   movieCd | movieNm                              | openDt     |   audiCnt |   rnum |   rank |
|----------:|:-------------------------------------|:-----------|----------:|-------:|-------:|
|  20235697 | 엔시티 네이션 : 투 더 월드 인 시네마 | 2023-12-06 |        69 |     23 |     23 |
|  20232077 | 어른 김장하                          | 2023-11-15 |        31 |     24 |     24 |
|  20227525 | 교토에서 온 편지                     | 2023-12-06 |        29 |     25 |     25 |